/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivatumoPolitikaRouteImport } from './routes/privatumo-politika'
import { Route as PristatymoPolitikaRouteImport } from './routes/pristatymo-politika'
import { Route as NaudojimoSalygosRouteImport } from './routes/naudojimo-salygos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const PrivatumoPolitikaRoute = PrivatumoPolitikaRouteImport.update({
  id: '/privatumo-politika',
  path: '/privatumo-politika',
  getParentRoute: () => rootRouteImport,
} as any)
const PristatymoPolitikaRoute = PristatymoPolitikaRouteImport.update({
  id: '/pristatymo-politika',
  path: '/pristatymo-politika',
  getParentRoute: () => rootRouteImport,
} as any)
const NaudojimoSalygosRoute = NaudojimoSalygosRouteImport.update({
  id: '/naudojimo-salygos',
  path: '/naudojimo-salygos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/naudojimo-salygos': typeof NaudojimoSalygosRoute
  '/pristatymo-politika': typeof PristatymoPolitikaRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/naudojimo-salygos': typeof NaudojimoSalygosRoute
  '/pristatymo-politika': typeof PristatymoPolitikaRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/naudojimo-salygos': typeof NaudojimoSalygosRoute
  '/pristatymo-politika': typeof PristatymoPolitikaRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/naudojimo-salygos'
    | '/pristatymo-politika'
    | '/privatumo-politika'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/naudojimo-salygos'
    | '/pristatymo-politika'
    | '/privatumo-politika'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/naudojimo-salygos'
    | '/pristatymo-politika'
    | '/privatumo-politika'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  NaudojimoSalygosRoute: typeof NaudojimoSalygosRoute
  PristatymoPolitikaRoute: typeof PristatymoPolitikaRoute
  PrivatumoPolitikaRoute: typeof PrivatumoPolitikaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privatumo-politika': {
      id: '/privatumo-politika'
      path: '/privatumo-politika'
      fullPath: '/privatumo-politika'
      preLoaderRoute: typeof PrivatumoPolitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pristatymo-politika': {
      id: '/pristatymo-politika'
      path: '/pristatymo-politika'
      fullPath: '/pristatymo-politika'
      preLoaderRoute: typeof PristatymoPolitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/naudojimo-salygos': {
      id: '/naudojimo-salygos'
      path: '/naudojimo-salygos'
      fullPath: '/naudojimo-salygos'
      preLoaderRoute: typeof NaudojimoSalygosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  NaudojimoSalygosRoute: NaudojimoSalygosRoute,
  PristatymoPolitikaRoute: PristatymoPolitikaRoute,
  PrivatumoPolitikaRoute: PrivatumoPolitikaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
